# Generated by Django 4.2.4 on 2023-10-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_delete_detalleventa_delete_permisos_delete_roles_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Departamentos',
        ),
        migrations.DeleteModel(
            name='Municipios',
        ),
    ]
