# Generated by Django 4.2.4 on 2023-10-18 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=25)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fechareg', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(default=1)),
                ('totalCompra', models.FloatField()),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecompra',
            fields=[
                ('id_detallecompra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_uni', models.FloatField()),
                ('precio_tot', models.FloatField()),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'detallecompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('id_detalleventa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_uni', models.FloatField()),
                ('precio_tot', models.FloatField()),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'detalleventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=75)),
                ('descripcion', models.CharField(max_length=1000)),
                ('cantidad', models.IntegerField()),
                ('fechaven', models.DateTimeField()),
                ('sabor', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=45)),
                ('estado', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=65)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=65)),
                ('direccion', models.CharField(max_length=50)),
                ('informacion_adicional', models.TextField()),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento_nit', models.CharField(max_length=50)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fechareg', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(default=1)),
                ('totalVenta', models.FloatField()),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
    ]
