# Generated by Django 4.2.4 on 2023-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=65)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=65)),
                ('estado', models.IntegerField(default=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
    ]
