# Generated by Django 4.2.4 on 2023-10-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproviders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='direccion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='informacion_adicional',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='numero_documento_nit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='tipo_documento',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
