# Generated by Django 4.2.4 on 2023-10-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Departamentos',
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
        migrations.DeleteModel(
            name='Municipios',
        ),
    ]
