# Generated by Django 4.2.4 on 2023-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=75)),
                ('descripcion', models.CharField(max_length=1000)),
                ('cantidad', models.PositiveIntegerField()),
                ('fechaven', models.DateField()),
                ('sabor', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estado', models.PositiveIntegerField(default=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
    ]
